### ISSUE TITLE
Job Management

### ISSUE THREAD

**Issue by julietrinh1** [lyeskara/SOEN390#14]
- job posting
- removal of posting
- set or change deadlines
- configure the documents mandatory to apply
- advertise third party platform
**User Stories**
- [x] #20 
- [x] #28 
- [x] #29 
- [x] #30 
- [x] #31 
- [x] #32 
- [x] #33 
- [x] #37 
- [x] #38 
- [x] #39 
- [x] #40

**Comment by LeonZhang7** [comment]
User stories apart of this epic have all been finished
